# Font
font_family JetBrains Mono Nerd Font
italic_font auto
bold_italic_font auto
font_size 11.0

# Theme
foreground #f8f8f2
background #151515
url_color #81A2BE

# Cursor
cursor #ffffff

# Window
background_opacity 1.00

color0  #000000
color8  #808080

color1  #CC6666
color9  #CC6666

color2  #A9D3AB
color10 #A9D3AB

color3  #F0C674
color11 #F0C674

color4  #81A2BE
color12 #81A2BE

color5  #B293BB
color13 #B293BB

color6  #8ABEB7
color14 #8ABEB7

color7  #FFFEFE
color15 #FFFEFE
