#!/bin/sh


#    █████████               █████                      █████                         █████
#   ███░░░░░███             ░░███                      ░░███                         ░░███
#  ░███    ░███  █████ ████ ███████    ██████   █████  ███████    ██████   ████████  ███████
#  ░███████████ ░░███ ░███ ░░░███░    ███░░███ ███░░  ░░░███░    ░░░░░███ ░░███░░███░░░███░
#  ░███░░░░░███  ░███ ░███   ░███    ░███ ░███░░█████   ░███      ███████  ░███ ░░░   ░███
#  ░███    ░███  ░███ ░███   ░███ ███░███ ░███ ░░░░███  ░███ ███ ███░░███  ░███       ░███ ███
#  █████   █████ ░░████████  ░░█████ ░░██████  ██████   ░░█████ ░░████████ █████      ░░█████
# ░░░░░   ░░░░░   ░░░░░░░░    ░░░░░   ░░░░░░  ░░░░░░     ░░░░░   ░░░░░░░░ ░░░░░        ░░░░░


riverctl spawn "waybar &"
riverctl spawn "swaybg -i ~/Pictures/Wallpapers/chill/painting.jpg"
riverctl spawn "swayidle -w"
riverctl spawn "mako"
riverctl spawn "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"
riverctl spawn "/usr/lib/polkit-kde-authentication-agent-1"


#   █████████            █████     █████     ███
#  ███░░░░░███          ░░███     ░░███     ░░░
# ░███    ░░░   ██████  ███████   ███████   ████  ████████    ███████  █████
# ░░█████████  ███░░███░░░███░   ░░░███░   ░░███ ░░███░░███  ███░░███ ███░░
#  ░░░░░░░░███░███████   ░███      ░███     ░███  ░███ ░███ ░███ ░███░░█████
#  ███    ░███░███░░░    ░███ ███  ░███ ███ ░███  ░███ ░███ ░███ ░███ ░░░░███
# ░░█████████ ░░██████   ░░█████   ░░█████  █████ ████ █████░░███████ ██████
#  ░░░░░░░░░   ░░░░░░     ░░░░░     ░░░░░  ░░░░░ ░░░░ ░░░░░  ░░░░░███░░░░░░
#                                                            ███ ░███
#                                                           ░░██████
#                                                            ░░░░░░

# Set keyboard layout
riverctl keyboard-layout it

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

riverctl focus-follows-cursor always
riverctl hide-cursor timeout 10000 # 10 Seconds in milliseconds
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-focus-change
riverctl set-repeat 50 300

# Touchpad Settings
# Get device name from riverctl list-inputs
riverctl input "pointer-1739-52545-SYNA7DB5:01_06CB:CD41_Touchpad" tap enabled
riverctl input "pointer-1739-52545-SYNA7DB5:01_06CB:CD41_Touchpad" accel-profile flat
riverctl input "pointer-1739-52545-SYNA7DB5:01_06CB:CD41_Touchpad" natural-scroll enabled
riverctl input "pointer-1739-52545-SYNA7DB5:01_06CB:CD41_Touchpad" disable-while-typing enabled
riverctl input "pointer-1739-52545-SYNA7DB5:01_06CB:CD41_Touchpad" disable-while-trackpointing enabled

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &


#  ███████████   ███                 █████
# ░░███░░░░░███ ░░░                 ░░███
#  ░███    ░███ ████  ████████    ███████   █████
#  ░██████████ ░░███ ░░███░░███  ███░░███  ███░░
#  ░███░░░░░███ ░███  ░███ ░███ ░███ ░███ ░░█████
#  ░███    ░███ ░███  ░███ ░███ ░███ ░███  ░░░░███
#  ███████████  █████ ████ █████░░████████ ██████
# ░░░░░░░░░░░  ░░░░░ ░░░░ ░░░░░  ░░░░░░░░ ░░░░░░


# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.
terminal="foot"
filemanager="thunar"
browser="librewolf"
mod="Mod4"

riverctl map normal Super Return spawn "$terminal"
riverctl map normal Super E spawn "$filemanager"
riverctl map normal Super W spawn "$browser"
riverctl map normal Super R spawn "rofi -show drun"
riverctl map normal $mod Escape spawn "~/.config/rofi/scripts/rofi-power"

riverctl map normal $mod+Control R spawn "$HOME/.config/river/init >/dev/null && notify-send -t 1000 'Refreshed River'"
riverctl map normal Super V exec killall -SIGUSR1 waybar
riverctl map normal Super B exec killall -SIGUSR2 waybar

riverctl map normal Super Space toggle-float
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super Q close
riverctl map normal Super+Shift Q exit

# Screenshots
riverctl map normal None Print spawn "$HOME/scripts/screenshots/captureAll.sh"
riverctl map normal Control Print spawn "$HOME/scripts/screenshots/captureScreen.sh"
riverctl map normal Control+Shift Print spawn "$HOME/scripts/screenshots/captureArea.sh"

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Super Left focus-view next
riverctl map normal Super Right focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
riverctl map normal Super+Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -25
riverctl map normal Super+Alt+Shift J resize vertical 25
riverctl map normal Super+Alt+Shift K resize vertical -25
riverctl map normal Super+Alt+Shift L resize horizontal 25

# Multimedia keybinds
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super+Shift Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Shift Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Shift Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Shift Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal


#  ███████████              ████
# ░░███░░░░░███            ░░███
#  ░███    ░███  █████ ████ ░███   ██████   █████
#  ░██████████  ░░███ ░███  ░███  ███░░███ ███░░
#  ░███░░░░░███  ░███ ░███  ░███ ░███████ ░░█████
#  ░███    ░███  ░███ ░███  ░███ ░███░░░   ░░░░███
#  █████   █████ ░░████████ █████░░██████  ██████
# ░░░░░   ░░░░░   ░░░░░░░░ ░░░░░  ░░░░░░  ░░░░░░

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add ssd

riverctl rule-add -title "File Operation Progress"
riverctl rule-add -title confirm
riverctl rule-add -title dialog
riverctl rule-add -title download
riverctl rule-add -title notification
riverctl rule-add -title error
riverctl rule-add -title title 'Open File'
riverctl rule-add -title title 'branchdialog'

riverctl rule-add -title "Special Offers" float # Steam
riverctl rule-add -title "Friends List" float   # Steam
riverctl rule-add -title "Steam Settings" float # Steam

riverctl map-switch normal lid close "swaylock -f"

# Make all views with app-id "bar" and any title use client-side decorations
riverctl rule-add -app-id "bar" csd

