# Font
font_family	  JetBrains Mono Nerd Font
bold		  auto
italic_font	  auto
bold_italic	  auto
font_size	  11.0

# Window
hide_window_decorations	  yes
remember_window_size	  yes

# Opacity
background_opacity        0.85

# Theme
foreground	#BDC3C2
background	#000000

cursor		#EBDBB2
url_color	#d3a0bc

color		#646464
color8		#646464

color1		#F58E8E
color9		#F58E8E

color2		#A9D3AB
color10		#A9D3AB

color3		#FED37E
color11		#FED37E

color4		#7AABD4
color12		#7AABD4

color5		#D6ADD5
color13		#D6ADD5

color6		#79D4D5
color14		#79D4D5

color7		#D4D4D4
color15		#D4D4D4
